spring.application.name=barofarm_backend

spring.jpa.database=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# Database
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.url=jdbc:postgresql://centerbeam.proxy.rlwy.net:21361/railway
spring.datasource.username=postgres
spring.datasource.password=BJwUoKHCxLWLWIgyFCeCKkLoHzTZOJld

# ??? ?? ??
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=120000

server.servlet.encoding.force=true

# JWT ? Swagger ??
jwt.secret=VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
springdoc.swagger-ui.path=/swagger-ui.html

# Toss Payments
toss.base-url=https://api.tosspayments.com/v1
toss.secret-key=${TOSS_SECRET_KEY:test_sk_LlDJaYngro2yMOoyEMKmVezGdRpX}

# CORS (React ?? ?? ??)
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# WebClient ?? ???
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=INFO
